### ISSUE TITLE
Pedigreeexporte ab Argus

### ISSUE THREAD

**Issue by pvrqualitasag** [pvrqualitasag/quagzws-sidef#10]
Was: Pedigreeexporte   ab Argus mit   /qualstorzws01/data_zws/pedigree/prog/exportPedigree/exportPedigree.sh
Gewichtung: 3
Wer: mfi

**Comment by mspengeler** [comment]
Getestet für Milchschafe auf beverin container vs. castor
Wiederum Warnmeldung:
(process:9770): dconf-CRITICAL **: 07:56:47.985: unable to create directory '/run/user/501/dconf': Permission denied.  dconf will not work properly.

Ansonsten liefert es genau die gleichen Dateien.
Ordner exportPedigree in singularity_data_zws/pedigree/prog kopiert
