### ISSUE TITLE
Verarbeitung Interbull-ZW

### ISSUE THREAD

**Issue by pvrqualitasag** [pvrqualitasag/quagzws-sidef#32]
Was: Verarbeitung Interbull-ZW
Gewichtung: 8
Wer: mbw

**Comment by pvrqualitasag** [comment]
Gemäss Meldung von mbw in #zws_container vom 18.04.2019 ist das erledigt.
> Die Verarbeitung der ITB-ZW (ohne gmace) ist im container getestet und prog und par nach singularity_data_zws transferiert. Gleichzeitig mit dem Testen im container habe ich die Verarbeitung vereinfacht und weitgehend automatisiert. Ich werde noch eine entsprechende Anleitung in confluence erstellen.

**Comment by mberweger** [comment]
Verarbeitung GMACE ebenfalls abgeschlossen.
Anleitungen in confluence erstellt.
