### ISSUE TITLE
alle VMS-Auswertungen

### ISSUE THREAD

**Issue by pvrqualitasag** [pvrqualitasag/quagzws-sidef#35]
Was: alle VMS-Auswertungen
Gewichtung: 30
Wer: skn

**Comment by sknqualitasag** [comment]
- Programm im Python und Shell-Scripts scheinen keinen Problem zu verursachen
- Programm im C++ wo die Entwicklungsumgebung RStudio ist, scheinen keinen Problem zu verursachen
- Programm im Fortran sind von Compiler abhängig. Es wurde bei Abstammungszuchtwerte Rundungsdifferenz festgestellt. (z.K. @mspengeler )

**Comment by sknqualitasag** [comment]
Im Moment wurden die ZWS für Schlachtmerkmalen, Absetzgewicht und Abstammungszuchtwerte getestet. ZWS für Geburtsablauf bei VMS läuft noch auf Mac.
