### ISSUE TITLE
Abstammungszuchtwertberechnung

### ISSUE THREAD

**Issue by pvrqualitasag** [pvrqualitasag/quagzws-sidef#42]
Was: Abstammungszuchtwertberechnung
Gewichtung: 5
Wer: mfi

**Comment by mspengeler** [comment]
Schritte nach Anleitung:
Abstammungs-ZW berechnen: runAbstZw_bv_jerh.sh wurde getestet
-> Rundungsdifferenzen bei Rel zwischen 0.12 und 0.13
changeAbstZwIps.sh wurde auch genutzt (sed um Pfade zu ersetzen)
LBE Gesamtnote BV und JE wurde nicht getestet, da calcGesBv.py und calcGesJe.py bereits in singularity_data_zws vorhanden sind
Feedsaved bei rh wurde ebenfalls aus gleichem Grund nicht getestet (calcZwFeedSaved.py)
LBE auf Rassebasis korrigieren: bkorr.f90 -> auch schon getestet
Importdateien für DB:
abstZwToDB.sh getestet: Neu werden auch Tiere mit * in der ID aufbereitet (von makeFilesforDB).
Fleisch: run_abstZW_dairy.sh: Wird getestet sobald VMS Routine files vorhanden sind

**Comment by mspengeler** [comment]
run_abstZW_dairy.sh getestet
